# Generated by Django 6.0.2 on 2026-02-28 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_alter_building_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('building', 'floor', 'number')},
        ),
    ]
