# Generated by Django 6.0.2 on 2026-02-27 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0003_alter_student_acceptance_type_alter_student_degree_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Charge', 'مطلوب'), ('Payment', 'مدفوع')], max_length=10)),
                ('fee_type', models.CharField(choices=[('registration', 'رسوم تسجيل'), ('semester', 'رسوم فصل'), ('late', 'رسوم تأخير'), ('clinic', 'رسوم استخدام العيادة'), ('transcript', 'رسوم اصدار اثبات طالب'), ('clearance', 'رسوم براءة ذمة'), ('other', 'رسوم أخرى')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('semester', models.IntegerField(blank=True, choices=[(1, 'First Semester'), (2, 'Second Semester'), (3, 'Summer Semester')], null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('is_system_generated', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_created', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='students.student')),
            ],
        ),
    ]
