# Generated by Django 6.0.2 on 2026-03-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='fee_type',
            field=models.CharField(choices=[('رسوم تسجيل', 'registration'), ('رسوم فصل', 'semester'), ('رسوم تأخير', 'late'), ('رسوم استخدام العيادة', 'clinic'), ('رسوم اصدار اثبات طالب', 'transcript'), ('رسوم براءة ذمة', 'clearance'), ('other', 'رسوم أخرى')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('مطلوب', 'Charge'), ('مدفوع', 'Payment')], max_length=10),
        ),
    ]
