# Generated by Django 6.0.2 on 2026-03-05 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_transaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='fee_type',
            field=models.CharField(choices=[('رسوم تسجيل', 'registration'), ('رسوم فصل', 'semester'), ('رسوم تأخير', 'late'), ('رسوم استخدام العيادة', 'clinic'), ('رسوم اصدار اثبات طالب', 'transcript'), ('رسوم براءة ذمة', 'clearance'), ('رسوم أخرى', 'other')], max_length=50),
        ),
    ]
