# Generated by Django 6.0.2 on 2026-03-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_transaction_fee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='fee_type',
            field=models.CharField(choices=[('registration', 'رسوم تسجيل'), ('semester', 'رسوم فصل'), ('late', 'رسوم تأخير'), ('clinic', 'رسوم استخدام العيادة'), ('transcript', 'رسوم اصدار اثبات طالب'), ('clearance', 'رسوم براءة ذمة'), ('other', 'رسوم أخرى')], max_length=50),
        ),
    ]
