# Generated by Django 6.0.2 on 2026-03-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_transaction_fee_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('charge', 'مستحق'), ('payment', 'مدفوع'), ('refund', 'مسترد')], max_length=10, null=True),
        ),
    ]
