# Generated by Django 6.0.2 on 2026-03-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('charge', 'مستحق'), ('payment', 'مدفوع'), ('refund', 'مسترد')], max_length=10),
        ),
    ]
