# Generated by Django 6.0.2 on 2026-03-07 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_service',
            field=models.BooleanField(default=False),
        ),
    ]
