# Generated by Django 6.0.2 on 2026-02-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_college_head_department_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='hour_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
