# Generated by Django 6.0.2 on 2026-03-05 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_major_hour_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='major',
            old_name='hour_price',
            new_name='hour_fee',
        ),
    ]
