# Generated by Django 6.0.2 on 2026-03-09 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_rename_hour_price_major_hour_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorSubjectRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(choices=[('university_required', 'متطلب جامعي اجباري'), ('university_elective', 'متطلب جامعي اختياري'), ('college_required', 'متطلب كلية اجباري'), ('major_required', 'متطلب تخصص اجباري'), ('major_elective', 'متطلب تخصص اختياري'), ('corrective', 'استدراكي')], max_length=30)),
                ('required_hours', models.IntegerField()),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_requirements', to='academics.major')),
            ],
            options={
                'unique_together': {('major', 'subject_type')},
            },
        ),
    ]
