# Generated by Django 6.0.2 on 2026-02-26 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('first_name_ar', models.CharField(blank=True, max_length=30)),
                ('last_name_ar', models.CharField(blank=True, max_length=30)),
                ('national_id', models.CharField(max_length=10, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('ذكر', 'Male'), ('أنثى', 'Female')], max_length=10)),
                ('nationality', models.CharField(blank=True, max_length=30)),
                ('employee_id', models.CharField(max_length=10, unique=True)),
                ('rank', models.CharField(blank=True, choices=[('محاضر', 'Lecturer'), ('أستاذ مساعد', 'Assistant Professor'), ('أستاذ مشارك', 'Associate Professor'), ('أستاذ', 'Professor')], max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instructors', to='academics.college')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instructors', to='academics.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
