# Generated by Django 6.0.2 on 2026-02-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='rank',
            field=models.CharField(blank=True, choices=[('Lecturer', 'محاضر'), ('Assistant Professor', 'أستاذ مساعد'), ('Associate Professor', 'أستاذ مشارك'), ('Professor', 'أستاذ')], max_length=50),
        ),
    ]
