# Generated by Django 6.0.2 on 2026-02-28 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_major_hour_price'),
        ('instructors', '0002_alter_instructor_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instructors', to='academics.college'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instructors', to='academics.department'),
        ),
    ]
