# Generated by Django 6.0.2 on 2026-02-27 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_college_head_department_head'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('father_name', models.CharField(blank=True, max_length=30)),
                ('grandfather_name', models.CharField(blank=True, max_length=30)),
                ('first_name_ar', models.CharField(blank=True, max_length=30)),
                ('father_name_ar', models.CharField(blank=True, max_length=30)),
                ('grandfather_name_ar', models.CharField(blank=True, max_length=30)),
                ('last_name_ar', models.CharField(blank=True, max_length=30)),
                ('national_id', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(blank=True, choices=[('ذكر', 'Male'), ('أنثى', 'Female')], max_length=10)),
                ('nationality', models.CharField(blank=True, max_length=30)),
                ('high_school_branch', models.CharField(blank=True, max_length=50)),
                ('high_school_average', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('high_school_country', models.CharField(blank=True, max_length=50)),
                ('high_school_district', models.CharField(blank=True, max_length=50)),
                ('student_id', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('degree', models.CharField(blank=True, choices=[('دبلوم', 'Diploma'), ('بكالوريوس', 'Bachelor'), ('ماجستير', 'Master'), ('دكتوراه', 'PhD')], max_length=50)),
                ('funding_entity', models.CharField(blank=True, choices=[('قرض', 'Loan'), ('خاص', 'Private'), ('منحة', 'Scholarship')], max_length=50)),
                ('acceptance_type', models.CharField(blank=True, choices=[('تنافسي', 'Competitive'), ('موازي', 'Parallel')], max_length=50)),
                ('study_type', models.CharField(blank=True, choices=[('نظامي', 'Regular'), ('انتساب', 'Affiliation')], max_length=50)),
                ('enrollment_year', models.IntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.college')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.major')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(choices=[(1, 'First Semester'), (2, 'Second Semester'), (3, 'Summer Semester')])),
                ('year', models.IntegerField()),
                ('mid_term_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('participation_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('final_term_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='courses.coursesection')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'section')},
            },
        ),
    ]
