# Generated by Django 6.0.2 on 2026-02-27 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='year',
        ),
        migrations.CreateModel(
            name='HourRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(choices=[(1, 'First Semester'), (2, 'Second Semester'), (3, 'Summer Semester')])),
                ('year', models.IntegerField()),
                ('requested_hours', models.IntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hour_registrations', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'semester', 'year')},
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='hour_registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='students.hourregistration'),
        ),
    ]
