# Generated by Django 6.0.2 on 2026-02-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_enrollment_semester_remove_enrollment_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='acceptance_type',
            field=models.CharField(blank=True, choices=[('Competitive', 'تنافسي'), ('Parallel', 'موازي')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='degree',
            field=models.CharField(blank=True, choices=[('Diploma', 'دبلوم'), ('Bachelor', 'بكالوريوس'), ('Master', 'ماجستير'), ('PhD', 'دكتوراه')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='funding_entity',
            field=models.CharField(blank=True, choices=[('Loan', 'قرض'), ('Private', 'خاص'), ('Scholarship', 'منحة')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'ذكر'), ('Female', 'أنثى')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='study_type',
            field=models.CharField(blank=True, choices=[('Regular', 'نظامي'), ('Affiliation', 'انتساب')], max_length=50),
        ),
    ]
