# Generated by Django 6.0.2 on 2026-02-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_acceptance_type_alter_student_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
