# Generated by Django 6.0.2 on 2026-02-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_status',
            field=models.CharField(blank=True, choices=[('Active', 'على مقاعد الدراسة'), ('Graduating', 'متوقع تخرجه'), ('Graduated', 'متخرج'), ('Suspended', 'موقوف'), ('Dropped', 'منسحب')], max_length=50),
        ),
    ]
