# Generated by Django 6.0.2 on 2026-03-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_absence'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourregistration',
            name='paid_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='max_hours',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='student',
            name='min_hours',
            field=models.IntegerField(default=12),
        ),
    ]
