# Generated by Django 6.0.2 on 2026-03-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_hourregistration_paid_hours_student_max_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='grade',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='grade_points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='symbol',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='weighted_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='final_term_grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='mid_term_grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='participation_grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
