# Generated by Django 6.0.2 on 2026-03-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_remove_enrollment_grade_enrollment_grade_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourregistration',
            name='semester',
            field=models.IntegerField(choices=[(1, 'الفصل الاول'), (2, 'الفصل الثاني'), (3, 'الفصل الصيفي')]),
        ),
    ]
