# Generated by Django 6.0.2 on 2026-03-09 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_hourregistration_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='announcements_last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
