# Generated by Django 6.0.2 on 2026-04-20 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_student_announcements_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('active', 'مسجل'), ('dropped', 'منسحب')], default='active', max_length=10),
        ),
    ]
