# Generated by Django 6.0.2 on 2026-02-27 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_college_head_department_head'),
        ('facilities', '0001_initial'),
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('hours', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='academics.department')),
                ('majors', models.ManyToManyField(related_name='subjects', to='academics.major')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(choices=[(1, 'First Semester'), (2, 'Second Semester'), (3, 'Summer Semester')])),
                ('year', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='instructors.instructor')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='facilities.room')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='courses.subject')),
            ],
        ),
    ]
