# Generated by Django 6.0.2 on 2026-02-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(blank=True, choices=[('متطلب جامعي اجباري', 'University Requirement'), ('متطلب جامعي اختياري', 'University Elective'), ('متطلب كلية اجباري', 'College Requirement'), ('متطلب تخصص اجباري', 'Major Requirement'), ('متطلب تخصص اختياري', 'Major Elective'), ('استدراكي', 'Corrective')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='semester',
            field=models.IntegerField(choices=[('First Semester', 1), ('Second Semester', 2), ('Summer Semester', 3)]),
        ),
    ]
