# Generated by Django 6.0.2 on 2026-02-28 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_subject_subject_type_alter_coursesection_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesection',
            name='semester',
            field=models.IntegerField(choices=[(1, 'First Semester'), (2, 'Second Semester'), (3, 'Summer Semester')]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(blank=True, choices=[('University Requirement', 'متطلب جامعي اجباري'), ('University Elective', 'متطلب جامعي اختياري'), ('College Requirement', 'متطلب كلية اجباري'), ('Major Requirement', 'متطلب تخصص اجباري'), ('Major Elective', 'متطلب تخصص اختياري'), ('Corrective', 'استدراكي')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='SectionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='courses.coursesection')),
            ],
        ),
    ]
