# Generated by Django 6.0.2 on 2026-03-04 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_examschedule'),
        ('facilities', '0003_alter_room_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='examschedule',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exam_schedules', to='facilities.room'),
        ),
    ]
