# Generated by Django 6.0.2 on 2026-03-04 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_examschedule_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesection',
            name='semester',
            field=models.IntegerField(choices=[('الفصل الأول', 1), ('الفصل الثاني', 2), ('الصيفي', 3)]),
        ),
        migrations.AlterField(
            model_name='sectionschedule',
            name='day',
            field=models.IntegerField(choices=[('ح', 0), ('ن', 1), ('ث', 2), ('ر', 3), ('خ', 4), ('ج', 5), ('س', 6)]),
        ),
    ]
