# Generated by Django 6.0.2 on 2026-03-07 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_coursesection_semester_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(choices=[(1, 'First Semester'), (2, 'Second Semester'), (3, 'Summer Semester')])),
                ('year', models.IntegerField()),
                ('symbol', models.CharField(choices=[('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('F*', 'F*')], max_length=5)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_distributions', to='courses.subject')),
            ],
            options={
                'ordering': ['-percentage'],
                'unique_together': {('subject', 'semester', 'year', 'symbol')},
            },
        ),
    ]
