# Generated by Django 6.0.2 on 2026-03-07 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_gradedistribution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectionschedule',
            options={'ordering': ['day', 'start_time']},
        ),
        migrations.AlterField(
            model_name='sectionschedule',
            name='day',
            field=models.CharField(choices=[('ح', 'Sunday'), ('ن', 'Monday'), ('ث', 'Tuesday'), ('ر', 'Wednesday'), ('خ', 'Thursday'), ('ج', 'Friday'), ('س', 'Saturday')], max_length=2),
        ),
        # 1. remove old unique_together first
        migrations.AlterUniqueTogether(
            name='examschedule',
            unique_together=set(),
        ),
        # 2. remove old subject field
        migrations.RemoveField(
            model_name='examschedule',
            name='subject',
        ),
        # 3. add new section field
        migrations.AddField(
            model_name='examschedule',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='courses.coursesection'),
        ),
        # 4. now set the new unique_together
        migrations.AlterUniqueTogether(
            name='examschedule',
            unique_together={('section', 'mid')},
        ),
    ]