# Generated by Django 6.0.2 on 2026-03-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_sectionschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesection',
            name='semester',
            field=models.IntegerField(choices=[(1, 'الفصل الأول'), (2, 'الفصل الثاني'), (3, 'الفصل الصيفي')]),
        ),
        migrations.AlterField(
            model_name='gradedistribution',
            name='semester',
            field=models.IntegerField(choices=[(1, 'الفصل الاول'), (2, 'الفصل الثاني'), (3, 'الفصل الصيفي')]),
        ),
    ]
