# Generated by Django 6.0.2 on 2026-03-07 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_coursesection_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='required_for', to='courses.subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(blank=True, choices=[('university_required', 'متطلب جامعي اجباري'), ('university_elective', 'متطلب جامعي اختياري'), ('college_required', 'متطلب كلية اجباري'), ('major_required', 'متطلب تخصص اجباري'), ('major_elective', 'متطلب تخصص اختياري'), ('corrective', 'استدراكي')], max_length=30, null=True),
        ),
    ]
