# Generated by Django 6.0.2 on 2026-03-23 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_subject_prerequisites_alter_subject_subject_type'),
        ('students', '0010_student_announcements_last_seen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(choices=[(1, 'First Semester'), (2, 'Second Semester'), (3, 'Summer Semester')])),
                ('year', models.IntegerField()),
                ('overall_start', models.DateField()),
                ('overall_end', models.DateField()),
                ('is_open', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('semester', 'year')},
            },
        ),
        migrations.CreateModel(
            name='RegistrationWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_hours', models.IntegerField()),
                ('max_hours', models.IntegerField()),
                ('start_date', models.DateField()),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='courses.registrationperiod')),
            ],
            options={
                'ordering': ['min_hours'],
            },
        ),
        migrations.CreateModel(
            name='SectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_requests', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='courses.coursesection')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_requests', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'section')},
            },
        ),
    ]
