# Generated by Django 6.0.2 on 2026-04-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_registrationperiod_registrationwindow_sectionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationwindow',
            name='end_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
