# Generated by Django 6.0.2 on 2026-04-11 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_registrationwindow_end_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrationwindow',
            options={'ordering': ['min_hours', 'start_datetime']},
        ),
        migrations.RemoveField(
            model_name='registrationwindow',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='registrationwindow',
            name='start_date',
        ),
        migrations.AddField(
            model_name='registrationwindow',
            name='end_datetime',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrationwindow',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 11, 13, 4, 19, 915885, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
