# Generated by Django 6.0.2 on 2026-04-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_registrationwindow_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesection',
            name='section_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
