# Generated by Django 6.0.2 on 2026-04-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_coursesection_section_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradedistribution',
            options={'ordering': ['-min_grade']},
        ),
        migrations.RenameField(
            model_name='gradedistribution',
            old_name='percentage',
            new_name='max_grade',
        ),
        migrations.AddField(
            model_name='gradedistribution',
            name='min_grade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
