# Generated by Django 6.0.2 on 2026-05-01 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_gradedistribution_options_and_more'),
        ('facilities', '0003_alter_room_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examschedule',
            name='room',
        ),
        migrations.AddField(
            model_name='examschedule',
            name='room',
            field=models.ManyToManyField(related_name='exam_schedules', to='facilities.room'),
        ),
    ]
