# Generated by Django 6.0.2 on 2026-05-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_remove_examschedule_room_examschedule_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionschedule',
            name='day',
            field=models.IntegerField(choices=[(0, 'ح'), (1, 'ن'), (2, 'ث'), (3, 'ر'), (4, 'خ'), (5, 'ج'), (6, 'س')], max_length=2),
        ),
    ]
