# Generated by Django 6.0.2 on 2026-05-08 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_sectionschedule_day'),
        ('instructors', '0003_alter_instructor_college_alter_instructor_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesection',
            name='instructor',
        ),
        migrations.AddField(
            model_name='sectionschedule',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='instructors.instructor'),
        ),
    ]
