# Generated by Django 6.0.2 on 2026-05-08 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_remove_coursesection_instructor_and_more'),
        ('facilities', '0003_alter_room_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesection',
            name='room',
        ),
        migrations.AddField(
            model_name='sectionschedule',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='facilities.room'),
        ),
    ]
