# Generated by Django 6.0.2 on 2026-05-08 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_remove_coursesection_room_sectionschedule_room'),
        ('facilities', '0003_alter_room_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionschedule',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='facilities.room'),
        ),
    ]
