# Generated by Django 6.0.2 on 2026-05-08 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_alter_sectionschedule_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesection',
            name='section_id',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
