# Generated by Django 6.0.2 on 2026-04-24 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0011_enrollment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('academic', 'أكاديمي'), ('financial', 'مالي'), ('technical', 'تقني'), ('other', 'أخرى')], max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('in_progress', 'قيد المعالجة'), ('closed', 'مغلق')], default='open', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response', models.TextField(blank=True)),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_responses', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
